name: "CI"

on:
  push:
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-11 ]
        tfversions: [ 0.13.7, 1.0.11, 1.1.0 ]
        modules: [ cloudtrail, config, config-rule, ebs-default-encryption, iam-access-analyzer, iam-password-policy, iam-userselfservice, secure-s3-bucket, security-hub ]
    runs-on: ${{ matrix.os }}

    env:
      AWS_REGION: 'eu-central-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.tfversions }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate modules/${{ matrix.modules }}
        id: validate-${{ matrix.modules }}
        working-directory: modules/${{ matrix.modules }}
        run: |
          terraform init -backend=false
          terraform validate
