name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'eu-central-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate modules/secure-s3-bucket
        id: validate-secure-s3-bucket
        working-directory: modules/secure-s3-bucket
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate modules/security-hub
        id: validate-security-hub
        working-directory: modules/security-hub
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate modules/cloudtrail
        id: validate-cloudtrail
        working-directory: modules/cloudtrail
        run: |
          terraform init -backend=false
          terraform validate
