name: "CI"

on:
  push:
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-11 ]
        tfversions: [ 0.13.7, 1.0.11, 1.1.0 ]
    runs-on: ${{ matrix.os }}

    env:
      AWS_REGION: 'eu-central-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.tfversions }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate modules/secure-s3-bucket
        id: validate-secure-s3-bucket
        working-directory: modules/secure-s3-bucket
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate modules/security-hub
        id: validate-security-hub
        working-directory: modules/security-hub
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate modules/cloudtrail
        id: validate-cloudtrail
        working-directory: modules/cloudtrail
        run: |
          terraform init -backend=false
          terraform validate
